### ISSUE TITLE
Open-source Checklist

### ISSUE THREAD

**Issue by tgolsson** [EmbarkStudios/cervo#4]
1. [x] Create a new private or internal repository on GitHub using the [open source template](https://github.com/EmbarkStudios/opensource-template). If you already have a repository and want to maintain the commit history, you can instead add all the files from the template repository to your project.
1. [x] Edit the `.github/CODEOWNERS` file to contain the GitHub usernames of the project maintainers.
1. [x] If the project is a Rust project edit `.github/workflows/rust-ci.yml` to your needs, resolving all the comments marked `TODO`.
1. [x] If the project is not a Rust project remove the `.github/workflows/rust-ci.yml` file.
1. [x] If the project is a Rust library project to be pushed to Crates.io publish an version publish of the crate with `cargo publish --token <TOKEN>` where `TOKEN` is and API token for the [`embark-studios`](https://crates.io/users/embark-studios) user. This shared bot account allows us to publish all crates under the same user and not have to worry about managing owners.
1. [x] Customise the README for your project by adding the appropriate name, description, links, and badges. This is also a great time to pick an emoji for the project!
1. [x] Add the [EmbarkStudios / Open Source Admins](https://github.com/orgs/EmbarkStudios/teams/open-source-admins) group as admins in the repo access settings. Ask for assistance on slack if you do not have access to the repo settings.
1. [x] Post the private repo link with a description of what it is to the Embark #opensource Slack channel and ask for green-light to go ahead. Do @mention your manager also for visibility.
1. [x] Make the repository public.
1. [x] Add the project to the [embark.dev list of open source projects](https://github.com/EmbarkStudios/opensource-website/blob/main/static/data/data.json).
1. [x] If the project is a Rust project add it to the [embark.rs list of open source Rust projects](https://github.com/EmbarkStudios/rust-ecosystem#open-source).
1. [ ] Announce the release on [our Discord](https://discord.gg/dAuKfZS) opensource channel and any other forums such as [/r/rust](https://reddit.com/r/rust). The ecosystem team can help you with this step. They will have the "community team" role on the Discord
